Repository Apptive-Game-Team/Lucy, pull requests merged in 2024-08, with the labels that each got.

#19 Fix about creature ai
  Assets/Creature_AI/Scripts/CreatureManager.cs
  Assets/JJW/Prefabs/JJW.prefab
  Assets/Scene/3F_Integrated.unity
Labels: bug

#21 fix - Develop : 덮어씌어졌던 변경사항 수정
  Assets/Creature_AI/Scripts/CreatureManager.cs
  Assets/Creature_AI/Scripts/MapBuilder.cs
  Assets/Creature_AI/Scripts/Util/PathFinder.cs
  Assets/KHJ/Scripts/CameraMove.cs
  Assets/Scene/3F_Integrated.unity
Labels: bug

#24 fix(shadow coordinate. item material)
  Assets/HIS/Prefabs/Item_Consume.prefab
  Assets/HIS/Prefabs/Item_Equipment.prefab
  Assets/LightSystem/Prefabs/LightSystem_3F_Integrated.prefab
Labels: fix

#30 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#31 27 빛을 피하는 몬스터 구현
  Assets/Creature_AI/Prefabs/Avoider.prefab
  Assets/Creature_AI/Prefabs/Avoider.prefab.meta
  Assets/Creature_AI/Scenes/3F_Integrated.unity
  Assets/Creature_AI/Scenes/3F_Integrated.unity.meta
  Assets/Creature_AI/Scripts/CreatureManager.cs
  Assets/Creature_AI/Scripts/Creatures.meta
  Assets/Creature_AI/Scripts/Creatures/Actor.cs
  Assets/Creature_AI/Scripts/Creatures/Actor.cs.meta
  Assets/Creature_AI/Scripts/Creatures/Avoider.cs
  Assets/Creature_AI/Scripts/Creatures/Avoider.cs.meta
  Assets/Creature_AI/Scripts/Creatures/Creature.cs
  Assets/Creature_AI/Scripts/Creatures/Creature.cs.meta
  Assets/Creature_AI/Scripts/Creatures/Guard.cs
  Assets/Creature_AI/Scripts/Creatures/Guard.cs.meta
  Assets/Creature_AI/Scripts/Creatures/Moster.cs
  Assets/Creature_AI/Scripts/Creatures/Moster.cs.meta
  Assets/Creature_AI/Scripts/Debuger.meta
  Assets/Creature_AI/Scripts/Debuger/MapBuilder.cs
  Assets/Creature_AI/Scripts/Debuger/MapBuilder.cs.meta
  Assets/Creature_AI/Scripts/HandLight.cs
  Assets/Creature_AI/Scripts/HandLight.cs.meta
  Assets/Creature_AI/Scripts/Player.cs
  Assets/Creature_AI/Scripts/Util/Detector.cs
  Assets/Creature_AI/Scripts/Util/PathFinder.cs
  Assets/Resources/TestResources.meta
  Assets/Resources/TestResources/Wall.png
  Assets/Resources/TestResources/Wall.png.meta
  Assets/Resources/TestResources/test_creature.png
  Assets/Resources/TestResources/test_creature.png.meta
  Assets/Resources/TestResources/test_player.jpg
  Assets/Resources/TestResources/test_player.jpg.meta
  ProjectSettings/TagManager.asset
Labels: feature

#35 34 stunnee on handlight
  Assets/Creature_AI/Prefabs/Stunnee.prefab
  Assets/Creature_AI/Prefabs/Stunnee.prefab.meta
  Assets/Creature_AI/Scenes/3F_Integrated.unity
  Assets/Creature_AI/Scripts/Creatures/Stunnee.cs
  Assets/Creature_AI/Scripts/Creatures/Stunnee.cs.meta
  Assets/Creature_AI/Scripts/HandLight.cs
Labels: feature

#36 feat(Sripts)
  Assets/JJW/Image/KakaoTalk_20240819_144917888.png
  Assets/JJW/Image/KakaoTalk_20240819_144917888.png.meta
  Assets/JJW/Image/Script_Image.png
  Assets/JJW/Image/Script_Image.png.meta
  Assets/JJW/Scenes/Test_0819.unity
  Assets/JJW/Scenes/Test_0819.unity.meta
  Assets/JJW/Scripts.meta
  Assets/JJW/Scripts/DialogueManager.cs
  Assets/JJW/Scripts/DialogueManager.cs.meta
  Assets/Scene/3F_Integrated.unity
Labels: feature

#38 37 refactor stunnee script
  Assets/Creature_AI/Scripts/Creatures/Avoider.cs
  Assets/Creature_AI/Scripts/Creatures/Stunnee.cs
  Assets/Creature_AI/Scripts/HandLight.cs
Labels: refactor

#42 feat(Door, Light Rotation)
  Assets/DoorSystem.meta
  Assets/DoorSystem/Prefabs.meta
  Assets/DoorSystem/Prefabs/DoorZone.prefab
  Assets/DoorSystem/Prefabs/DoorZone.prefab.meta
  Assets/DoorSystem/Prefabs/Door_3F.prefab
  Assets/DoorSystem/Prefabs/Door_3F.prefab.meta
  Assets/DoorSystem/Scripts.meta
  Assets/DoorSystem/Scripts/DoorObject.cs
  Assets/DoorSystem/Scripts/DoorObject.cs.meta
  Assets/JJW/Image/KakaoTalk_20240819_154902636.png
  Assets/JJW/Image/KakaoTalk_20240819_154902636.png.meta
  Assets/JJW/Image/KakaoTalk_20240819_154902636_01.png
  Assets/JJW/Image/KakaoTalk_20240819_154902636_01.png.meta
  Assets/KHJ/Sprites/Player.prefab
  Assets/LightSystem/Prefabs/HandLightComponent.prefab
  Assets/LightSystem/Prefabs/HandLightComponent.prefab.meta
  Assets/LightSystem/Scripts.meta
  Assets/LightSystem/Scripts/HandLightManager.cs
  Assets/LightSystem/Scripts/HandLightManager.cs.meta
  Assets/LightSystem/Scripts/HandLightRotator.cs
  Assets/LightSystem/Scripts/HandLightRotator.cs.meta
  Assets/LightSystem/Scripts/HandLightSwitch.cs
  Assets/LightSystem/Scripts/HandLightSwitch.cs.meta
Labels: feature

#50 배터리 ui업데이트 코드 추가
  Assets/HIS/Script/Inventory.cs
Labels: feature

#51 48 fix creature bug
  Assets/Creature_AI/Scripts/Util/PathFinder.cs
  Assets/Scene/3F_Merge_08.19.unity
Labels: fix

#74 인형 사라진거 수정, 손전등 체크 방식 변경
  Assets/HIS/Prefabs/Inventory_Item 1 1.prefab
  Assets/HIS/Script/Inventory.cs
  Assets/Scene/3F_Merge_08.19.unity
Labels: fix

#79 feat(Main, Puzzle)
  Assets/JJW/Image/KakaoTalk_20240819_203509999.png
  Assets/JJW/Image/KakaoTalk_20240819_203509999.png.meta
  Assets/JJW/Image/KakaoTalk_20240819_203509999_01.png
  Assets/JJW/Image/KakaoTalk_20240819_203509999_01.png.meta
  Assets/JJW/Image/KakaoTalk_20240819_203509999_02.png
  Assets/JJW/Image/KakaoTalk_20240819_203509999_02.png.meta
  Assets/JJW/Image/KakaoTalk_20240819_203509999_03.png
  Assets/JJW/Image/KakaoTalk_20240819_203509999_03.png.meta
  Assets/JJW/Image/puzzle1.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_01.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_01.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_02.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_02.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_03.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_03.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_04.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_04.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_05.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_05.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_06.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_06.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_07.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_07.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_08.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_08.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_09.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_09.png.meta
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_10.png
  Assets/JJW/Image/puzzle1/KakaoTalk_20240825_195804218_10.png.meta
  Assets/JJW/Prefabs/Tile.prefab
  Assets/JJW/Prefabs/Tile.prefab.meta
  Assets/JJW/Scenes/Puzzle1.unity
  Assets/JJW/Scenes/Puzzle1.unity.meta
  Assets/JJW/Scenes/Test2.unity
  Assets/JJW/Scenes/Test240819.unity
  Assets/JJW/Scenes/Test240819.unity.meta
  Assets/JJW/Scenes/Test_0819.unity
  Assets/JJW/Scenes/Text_Test.unity
  Assets/JJW/Scenes/Title.unity
  Assets/JJW/Scenes/Title.unity.meta
  Assets/JJW/Scripts/Puzzle1.meta
  Assets/JJW/Scripts/Puzzle1/CloseButton.cs
  Assets/JJW/Scripts/Puzzle1/CloseButton.cs.meta
  Assets/JJW/Scripts/Puzzle1/PuzzleManager.cs
  Assets/JJW/Scripts/Puzzle1/PuzzleManager.cs.meta
  Assets/JJW/Scripts/Puzzle1/StartButton.cs
  Assets/JJW/Scripts/Puzzle1/StartButton.cs.meta
  Assets/JJW/Scripts/ScreenSizeManager.cs
  Assets/JJW/Scripts/ScreenSizeManager.cs.meta
  Assets/JJW/Scripts/StartButton.cs
  Assets/JJW/Scripts/StartButton.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: documentation

#91 85 어두운 곳에 있을 때 정신력이 깎이는 시스템 구현
  Assets/CreatureAI/Scripts/Util/Detector.cs
  Assets/HIS/Script/Character_Stat.cs
  Assets/KHJ/Sprites/Player.prefab
  Assets/LightSystem/Prefabs/LightSystem_3F_Integrated.prefab
  Assets/LightSystem/Prefabs/Spot Light.prefab
  Assets/LightSystem/Prefabs/Spot Light.prefab.meta
  Assets/LightSystem/Scenes/LightTestScene_ver2.unity
  Assets/LightSystem/Scenes/LightTestScene_ver2.unity.meta
  Assets/LightSystem/Scripts/SpotLight.cs
  Assets/LightSystem/Scripts/SpotLight.cs.meta
Labels: feature

#95 83 손전등 초기 상태 변경/손전등 버그 수정
  Assets/HIS/Scenes/3F_Issue#83.unity
  Assets/HIS/Scenes/3F_Issue#83.unity.meta
  Assets/HIS/Script/FlashLight.cs
  Assets/HIS/Script/Inventory.cs
  Assets/LightSystem/Scripts/HandLightSwitch.cs
Labels: fix, feature

#100 튜토리얼 스토리 스크립트 출력
  Assets/KHJ/Scene/Tutorial_Test Scene_0830.unity
  Assets/KHJ/Scene/Tutorial_Test Scene_0830.unity.meta
  Assets/KHJ/Scripts/New Tutorial Dialogue Data.asset
  Assets/KHJ/Scripts/New Tutorial Dialogue Data.asset.meta
  Assets/KHJ/Scripts/TutorialController.cs
  Assets/KHJ/Scripts/TutorialController.cs.meta
  Assets/KHJ/Scripts/TutorialDialogueController.cs
  Assets/KHJ/Scripts/TutorialDialogueController.cs.meta
  Assets/KHJ/Scripts/TutorialDialogueData.cs
  Assets/KHJ/Scripts/TutorialDialogueData.cs.meta
  Assets/KHJ/Sprites/Background.png
  Assets/KHJ/Sprites/Background.png.meta
Labels: feature

#107 76 3층 씬에 오브젝트 배치 기획
  Assets/HIS/Prefabs/Inventory_Item 1 1.prefab
  Assets/HIS/Scenes/3F_Issue#76.unity
  Assets/HIS/Scenes/3F_Issue#76.unity.meta
  Assets/HIS/Script/FlashLight.cs
Labels: feature

#105 81 퍼즐 시스템과 퍼즐 방 연결
  Assets/JJW/Scripts/Puzzle1/CheckButton.cs
  Assets/JJW/Scripts/Puzzle1/CheckButton.cs.meta
  Assets/JJW/Scripts/Puzzle1/CloseButton.cs
  Assets/JJW/Scripts/Puzzle1/PuzzleInteract.cs
  Assets/JJW/Scripts/Puzzle1/PuzzleInteract.cs.meta
  Assets/JJW/Scripts/TestDialogueController.cs
  Assets/KHJ/Scene/Puzzle_TestScene_0831.unity
  Assets/KHJ/Scene/Puzzle_TestScene_0831.unity.meta
  Assets/KHJ/Scene/Test Scene.unity
  Assets/KHJ/Sprites/PuzzleBefore.png
  Assets/KHJ/Sprites/PuzzleBefore.png.meta
  Assets/KHJ/Sprites/PuzzleBefore.prefab
  Assets/KHJ/Sprites/PuzzleBefore.prefab.meta
Labels: feature
